/* Instruments */
import { combineReducers } from "@reduxjs/toolkit";
import {
  dashboardSlice,
  appSlice,
  anniversaryDialogSlice,
  notesSlice,
  tableInputNotesSlice,
  userNoteSlice,
  occasionalmessageSlice,
  NotificationManagementSlice,
  ticketsSlice,
  sendReportSlice,
  SurveySlice,
  loginSlice,
  groupsSlice,
  UserManagementSlice,
  StoreManagementSlice,
  ListofGroupsAdminSlice,
  SettingSlice,
  ViewSendReportSlice,
  lotterySlice,
} from "./slices";
import { AuthenticationSlice } from "./slices/AuthenticationSlice";

export const reducer = combineReducers({
  anniversaryDialog: anniversaryDialogSlice.reducer,
  app: appSlice.reducer,
  dashboard: dashboardSlice.reducer,
  groups: groupsSlice.reducer,
  login: loginSlice.reducer,
  lottery: lotterySlice.reducer,
  StoreManagement: StoreManagementSlice.reducer,
  Setting: SettingSlice.reducer,
  notes: notesSlice.reducer,
  occasionalMessage: occasionalmessageSlice.reducer,
  NotificationManagement: NotificationManagementSlice.reducer,
  sendReport: sendReportSlice.reducer,
  Survey: SurveySlice.reducer,
  tableInputNotes: tableInputNotesSlice.reducer,
  userNote: userNoteSlice.reducer,
  tickets: ticketsSlice.reducer,
  Authentication: AuthenticationSlice.reducer,
  UserManagement: UserManagementSlice.reducer,
  ListofGroupsAdmin: ListofGroupsAdminSlice.reducer,
  ViewSendReport:ViewSendReportSlice.reducer,
});
